# Generated by Django 5.0.2 on 2024-06-06 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HitTrainers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='trainers',
            name='gender_tr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='HitTrainers.gender'),
        ),
    ]
